version: '3'

services:

    nginx:
        image: nginx:latest
        volumes:
            - ./:/var/www
            - ./_docker/nginx/conf.d:/etc/nginx/conf.d
        ports:
            - 8889:80
        depends_on:
            - app
            - vite
        container_name: project_nginx

    app:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        volumes:
            - ./:/var/www
        depends_on:
            - db
        container_name: project_app

    vite:
        build:
            context: .
            dockerfile: _docker/vite/Dockerfile
        ports:
            - "5173:5173"
        volumes:
            - .:/var/www
        container_name: project_vite
        command: ["npm", "run", "dev"]

    db:
        image: mysql:8.0
        restart: always
        volumes:
            - ./tmp/db:/var/lib/mysql
        environment:
            MYSQL_DATABASE: home
            MYSQL_ROOT_PASSWORD: root
            TZ: "Europe/Kyiv"
        ports:
            - 8112:3306
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
        container_name: project_db

    phpmyadmin:

        image: phpmyadmin/phpmyadmin

        container_name: pma_home

        links:

            - db

        environment:

            PMA_HOST: db

            PMA_PORT: 3306

            PMA_ARBITRARY: 1

            TZ: "Europe/Kyiv"

        restart: always

        ports:

            - 8881:80
